version: '2.1'
services:
  node1:
    image: matrixbase/server
    ports:
      - "8081:8080"
      - "22101:22101"
      - "22201:22201"

    volumes:
      - ./cfg/node1.toml:/etc/cfg.toml

  node2:
    image: matrixbase/server
    ports:
      - "8082:8080"
      - "22102:22101"
      - "22202:22201"

    volumes:
      - ./cfg/node2.toml:/etc/cfg.toml

  node3:
    image: matrixbase/server
    ports:
      - "8083:8080"
      - "22103:22101"
      - "22203:22201"
    volumes:
      - ./cfg/node3.toml:/etc/cfg.toml
